### ISSUE TITLE
Add Validation for Organization Fields

### ISSUE THREAD

**Issue by wedgex** [rentpath/ankle_bracelets#1]
Name should be unique. Add unique db constraint as well.

Require and validate phone number.

Validate Zip Code if entered.

**Comment by jtheodore-rent** [comment]
Added validation for name, requiring that it be unique.

Phone number validation accepts 10-digit phone number with no dashes only

Zip code validation accepts 5-digit or zip-plus-4 format

Email validation accepts standard email format
